# Generated by Django 5.0.1 on 2024-01-09 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image_data',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
