# Generated by Django 5.0.1 on 2024-01-09 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_event_image_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image_data',
            field=models.BinaryField(null=True),
        ),
    ]
